alias cl='clear'
alias vi='vim'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Git wrapper for personal repos
function mygit() {
	ACTION=$1 && shift
	ARGS="$@"

	if [[ $ACTION != 'clone' ]]; then
		git config user.name 'Dan Stewart' >/dev/null 2>&1
		git config user.email 'danielandrewstewart@gmail.com' >/dev/null 2>&1
	fi

	GIT_SSH_COMMAND='ssh -i $HOME/.ssh/id_rsa_personal' git $ACTION $ARGS
}

function read_log() {
	file=$1
	perl -E'
	my $file = shift;

	open my $pipe, "-|", "/usr/bin/tail", "-0f", "$file" or die "Could not tail file: $!";
	$SIG{INT} = sub { close $pipe if $pipe; exit; }; # catch ctrl-c
	
	while (<$pipe>) {
		print unless /uninitialized|Prototype|mask|^\s*at|will not stay shared|Subroutine \w+ redefined|Constant subroutine|filename: /;
	}' $file
}

