default = "prompt"

[bash]
allow = [
    "git *",
    "grep *",
    "find *",
    "cat *",
    "ls *",
    "head *",
    "./script/test *",
    "tail *",
    "echo *",
]
prompt = [
    "rm -rf *",
    "sudo *",
	"git push *",
]

[read]
default = "allow"

[mcp.github]
deny = ["admin_delete"]
allow = [
    "pull_request_read",
]

[write]
allow = [
]
