# .bashrc

# ===== Sourcing other files =====
[[ -f /etc/bashrc ]] && . /etc/bashrc

# ===== History ===== #
shopt -s cmdhist  # Store multiline commands on one line in history
shopt -s histappend  # Append to history instead of overwriting
HISTTIMEFORMAT="%h %d %H:%M:%S "
HISTSIZE=10000
HISTFILESIZE=10000
HISTCONTROL=erasedups


# ===== Path ======
GO_PATH="/usr/local/go/bin"
BREW_PATH="/opt/homebrew/bin"

# Build $PATH
exists=()
paths=(
	"$HOME/bin"
	"$HOME/.local/bin"
	"$BREW_PATH"
	"$HOME/.local/bin"
	"$GO_PATH"
	"$HOME/.cargo/bin/"
	"/usr/local/go/bin/"
	"$HOME/go/bin/"
	"$HOME/.local/share/pypoetry/venv/bin/"
	"$HOME/.cache/rebar3/bin"
	"/opt/homebrew/sbin"
	"$HOME/.atuin/bin/"
)

# Filter non existent paths
for item in "${paths[@]}"; do [[ -e $item ]] && exists+=("$item"); done

PATH="$(IFS=: eval 'echo "${exists[*]}"'):$PATH"
export PATH


# ===== Settings =====
shopt -s checkwinsize  # Handle window size changes
shopt -s globstar  # Support ** globbing

if [[ -n $PS1 ]]; then
	[[ -f ~/.bash_aliases ]] && . ~/.bash_aliases && cd .
	[[ -f ~/.bash_funcs ]] && . ~/.bash_funcs
	[[ -f ~/.sensible.bash ]] && . ~/.sensible.bash
	[[ -f ~/.forgit.bash ]] && . ~/.forgit.bash
	[[ -f /etc/profile.d/vte.sh ]] && . /etc/profile.d/vte.sh

	shopt -s histverify  # Expand history before executing when using bangs
	#shopt -s direxpand  # Expand filenames
	shopt -s autocd  # When typing just a dir name, cd to it
	shopt -s cdspell  # Fix typos when cd-ing
	shopt -s dirspell  # Fix typos in dir names

	# Keys
	bind '"\t":menu-complete'
	bind '"\e[Z":menu-complete-backward'
	bind 'set mark-symlinked-directories on'
	bind '"\C-h": backward-kill-word'
	bind '"\e[3;5~": kill-word'

	stty werase undef
	bind '"\C-w": backward-kill-word'

	complete -d cd
fi

# Enable Docker BuildKit
export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1
export BUILDKIT_PROGRESS=plain

# ===== Colors =====
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# ===== Exports =====
# Coloured prompt
# https://i.sstatic.net/KTSQa.png
COLOR_DANGER="\033[38;5;160m"
COLOR_WARNING="\033[38;5;214m"
COLOR_SUCCESS="\033[38;5;120m"
COLOR_INFO="\033[38;5;117m"
COLOR_RESET="\e[0m"

COLOR_PROMPT_CWD="\033[38;5;152m"
COLOR_PROMPT_HOST="\033[38;5;228m"
COLOR_PROMPT_BRACKETS="\033[38;5;152m"

function colorize() {
	# Takes a color code and a string and echos that string in that color
	# Handles resetting the color afterwards
	color_code="$1"
	str="$2"
	[[ -n $str && $str != '' ]] && echo "\[$color_code\]$str\[$COLOR_RESET\]"
}

function git_color {
	git_status="$(git status 2> /dev/null)"
	[[ $? > 0 ]] && exit 0

	if [[ ! $git_status =~ "working tree clean" && ! $git_status =~ "working directory clean" ]]; then
		echo -e $COLOR_WARNING
	elif [[ $git_status =~ "Your branch is ahead of" ]]; then
		echo -e $COLOR_DANGER
	elif [[ $git_status =~ "nothing to commit" ]]; then
		echo -e $COLOR_SUCCESS
	else
		echo -e $COLOR_INFO
	fi
}

function git_branch {
	local git_status="$(git status 2> /dev/null)"
	local on_branch="On branch ([^${IFS}]*)"
	local on_commit="HEAD detached at ([^${IFS}]*)"

	if [[ $git_status =~ $on_branch ]]; then
		local branch=${BASH_REMATCH[1]}
		branch=$(echo $branch | rev | cut -d\/ -f1 | rev)  # Cut out stuff like 'user/feature/xyz' and just get the base branch name
		echo -n "($branch)"
	elif [[ $git_status =~ $on_commit ]]; then
		local commit=${BASH_REMATCH[1]}
		echo -n "($commit)"
	fi
}

function short_cwd {
	cwd_length=14
	cwd="${PWD/$HOME/\~}"

	if [[ $(echo $cwd | wc -c | tr -d " ") -gt $cwd_length ]]; then
		cwd=$(echo -n $cwd | awk -F '/' '{ print ".../" $(NF-1) "/" $(NF) }')
	else
		cwd="$(echo -n $cwd)"
	fi

	echo $cwd
}

standard_prompt="$(colorize $COLOR_PROMPT_BRACKETS '[')$(colorize $COLOR_PROMPT_HOST '\u@\h')$(colorize $COLOR_PROMPT_BRACKETS ']')"
color=git_color
branch=git_branch

export PROMPT_COMMAND='history -a; prompt="${standard_prompt} $(colorize $COLOR_PROMPT_CWD `short_cwd`) $(colorize `git_color` `git_branch`) \$ "; export PS1=${prompt//  / }'

command -v nvim >/dev/null && editor="nvim" || editor="vim"
export VISUAL='code'
export EDITOR=$editor
export SUDO_EDITOR=$editor
export PAGER="less"
export BAT_PAGER="less -XFR"
export LESS="--mouse --wheel-lines=3 -XFR"
export AWS_PAGER=""

# Server specific settings
if [[ $hostname == "web" || $hostname == "media" || $hostname == "pve" ]]; then
    export TERM="xterm-256color"
fi

# fzf
export FZF_DEFAULT_OPTS='--reverse --border --exact'
[[ -f ~/.fzf.bash ]] && source ~/.fzf.bash
[[ -f /usr/share/fzf/shell/key-bindings.bash ]] && source /usr/share/fzf/shell/key-bindings.bash
[[ -f /usr/share/doc/fzf/examples/key-bindings.bash ]] && source /usr/share/doc/fzf/examples/key-bindings.bash
[[ -f /usr/share/doc/fzf/examples/completion.bash ]] && source /usr/share/doc/fzf/examples/completion.bash

# Mac
if command -v brew >/dev/null; then
	# Auto complete
	[[ -f "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && source "$(brew --prefix)/etc/profile.d/bash_completion.sh"

	# Forgit
	[[ -f $(brew --prefix)/share/forgit/forgit.plugin.sh ]] && source $(brew --prefix)/share/forgit/forgit.plugin.sh

# Linux
else
	# Auto complete
	[[ -f /usr/local/etc/bash_completion ]] && source /usr/local/etc/bash_completion
fi


# SSH
eval $(ssh-agent -s) > /dev/null 2>&1
ssh-add $HOME/.ssh/id_rsa > /dev/null 2>&1
for i in $HOME/.ssh/*.pem; do
	ssh-add $i > /dev/null 2>&1
done

# Source Cargo env
if [[ -e "$HOME/.cargo/env" ]]; then
	source "$HOME/.cargo/env"
fi

# WSL specific stuff
if [[ -n $WSLENV ]]; then
	export WSL_ip_line=$(ipconfig.exe | grep "WSL" -n | awk -F ":" '{print $1+4}')
	export DISPLAY=$(ipconfig.exe | awk -v a=$WSL_ip_line '{if (NR==a) print $NF":0.0"}' | tr -d "\r")
	export LIBGL_ALWAYS_INDIRECT=1
fi

# Auto-activate hermit
if [[ -e $HOME/bin/hermit ]]; then
	eval "$(test -x $HOME/bin/hermit && $HOME/bin/hermit shell-hooks --print --bash)"
fi

# https://mise.jdx.dev/
if [[ -e $HOME/.local/bin/mise ]]; then
	eval "$($HOME/.local/bin/mise activate bash)"
elif [[ -e /opt/homebrew/bin/mise ]]; then
	eval "$(/opt/homebrew/bin/mise activate bash)"
fi

# https://direnv.net/
if command -v direnv >/dev/null 2>&1; then
	eval "$(direnv hook bash)"
fi

if [[ -f "~/.bash-preexec.sh" ]]; then
	source ~/.bash-preexec.sh
fi

# https://atuin.sh
if command -v atuin >/dev/null; then
	eval "$(atuin init bash --disable-up-arrow)"
	source "$HOME/.atuin/bin/env"
fi
