" To install vimplug
" curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

"=============
"== Plugins ==
"=============
call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
Plug 'scrooloose/nerdcommenter'
call plug#end()

"====================
"== Basic Settings ==
"====================
syntax on
set nocompatible
set bg=dark
set hls
set visualbell
set number
set background=dark
set hidden
set mouse=a
set timeoutlen=1000
set ttimeoutlen=0
set cursorline
set ignorecase
set smartcase
set clipboard+=unnamed
set clipboard+=unnamedplus
set showcmd
set cindent
set smartindent
set autoindent
set incsearch
set backspace=indent,eol,start
set encoding=utf-8
set fileencoding=utf-8
set lazyredraw
set splitbelow
set splitright
set scrolloff=10
map <SPACE> <leader>
colorscheme gruvbox

if &term =~ '256color'
	set t_ut=
endif

" perl
let perl_extended_vars=1

" tabs
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent

" folding
set foldmethod=syntax
set foldlevelstart=999
let perl_fold=1
let javaScript_fold=1
let xml_syntax_folding=1
let sh_fold_enabled=1
nmap <leader>ff za
" This needs some work
" Currently folds everything then unfolds one level
" Works great for perl modules but not really for JS
nmap <leader>fa zMzr
nmap <leader>fu zR

"=============
"== Plugins ==
"=============
" NerdCommenter
let g:NERDSpaceDelims=1
let g:NERDTrimTrailingWhitespace=1
nmap <C-c> <Plug>NERDCommenterToggle

"==================
"== Key Bindings ==
"==================
" general
nnoremap Q <nop>
nmap <leader>d <C-]>
nmap Y y$
nnoremap <silent> <Leader>/ :nohlsearch<CR>
inoremap <C-H> <C-W>

" semicolon to colon
nmap ; :

" map tab to tab selection in visual 
" and normal modes and shift tab to 
" untab
vmap <tab> >gv
vmap <S-tab> <gv
nmap <tab> I<tab><esc>
nmap <S-tab> ^i<bs><esc>

" navigate between buffers
" using Ctrl+Arrow
nnoremap <C-Right> :bn<CR>
vnoremap <C-Right> :bn<CR>
nnoremap <C-Left> :bp<CR>
vnoremap <C-Left> :bp<CR>

" navigate between buffers
" using leader
nnoremap <leader><Right> :bn<CR>
nnoremap <leader><Left> :bp<CR>
nnoremap <leader>bd :bd<CR>
nnoremap <leader>bu :bu<CR>

" toggle spell check
nmap <leader>ss :setlocal spell!<CR>

" navigate between windows
" using Shift+Arrow
nmap <silent> <S-Up> :wincmd k<CR>
nmap <silent> <S-Down> :wincmd j<CR>
nmap <silent> <S-Left> :wincmd h<CR>
nmap <silent> <S-Right> :wincmd l<CR>

" toggle whitespace
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<
noremap <F2> :set list!<CR>

